# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://dpg-d6f7v088tnhs73cjt7hg-a:5432/urlshortener_tzwj
spring.datasource.username=postgress
spring.datasource.password=S52r5UCCgTQdi7Kj1LfDcuZK3bLkqIZj
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect